on:
  push:
    branches:
      - main

  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Check TypeScript definitions
        run: npm run check:schema:ts

      - name: Verify that `npm run generate:json` did not change outputs (if it did, please re-run it and re-commit!)
        run: npm run check:schema:json